#!/bin/bash
DATE=$(date)
echo "Starting backup process!"
mysqldump -uSQL_userid -pSQL_pwd -hMySQLIP --all-databases --single-transaction | gzip > /backup/MyDatabase_$(date +%Y-%m-%d).sql.gz

#http://scratching.psybermonkey.net/2011/01/bash-how-to-check-exit-status-of-pipe.html
if [ ${PIPESTATUS[0]} -ne "0" ];
then
   echo "the command \"mysqldump\" failed with Error: ${PIPESTATUS[0]}";
   exit 1;   
else
   echo "MySQL Backup completed! $DATE";
fi


##Delete files "My*" older than BACKUPCOPIES days
find /backup/My* -mtime +BACKUPCOPIES -exec rm {} \;

   
#restore databases   
# gunzip < MyDatabase_DATE.sql.gz | mysql -uxbmc -h 192.168.0.40


#https://github.com/dockerfile/mariadb/issues/3
#TERM env variable


